export const GET_PEOPLE = 'GET_PEOPLE'
export const GET_PEOPLE_PENDING = 'GET_PEOPLE_PENDING'
export const GET_PEOPLE_FULFILLED = 'GET_PEOPLE_FULFILLED'
export const GET_PEOPLE_REJECTED = 'GET_PEOPLE_REJECTED'